overblog_graphql:
  definitions:
    schema:
      query: RootQuery
      mutation: RootMutation
      types: [ArticleTeaser, MediaTeaser, NewsTeaser, Image]
    mappings:
      types:
        - type: attribute
          dir: "%atoolo_graphql_search_bundle.src_dir%/Input"
          suffix: ~
        - type: attribute
          dir: "%atoolo_graphql_search_bundle.src_dir%/Types"
          suffix: ~
        - type: attribute
          dir: "%atoolo_graphql_search_bundle.src_dir%/Query"
          suffix: ~
        - type: attribute
          dir: "%atoolo_graphql_search_bundle.src_dir%/Mutation"
          suffix: ~
        - types: [yaml]
          dir: "%atoolo_graphql_search_bundle.src_dir%/Resources/schema/decorators"
          suffix: ~
        - types: [yaml]
          dir: "%atoolo_graphql_search_bundle.src_dir%/Resources/schema/types"
          suffix: ~
#        - types: [graphql]
#          dir: "%atoolo_graphql_search_bundle.src_dir%/Resources/schema"
#          suffix: ~

