overblog_graphql:
  definitions:
    schema:
      query: RootQuery
      mutation: RootMutation
      types: [ArticleTeaser, MediaTeaser, Image]
    mappings:
      types:
        - type: attribute
          dir: "%atoolo_graphql_search_bundle_src_dir%/Input"
          suffix: ~
        - type: attribute
          dir: "%atoolo_graphql_search_bundle_src_dir%/Types"
          suffix: ~
        - type: attribute
          dir: "%atoolo_graphql_search_bundle_src_dir%/Query"
          suffix: ~
        - type: attribute
          dir: "%atoolo_graphql_search_bundle_src_dir%/Mutation"
          suffix: ~
        - type: graphql
          dir: "%atoolo_graphql_search_bundle_src_dir%/Resources/schema"
          suffix: ~
        - type: yaml
          dir: "%atoolo_graphql_search_bundle_src_dir%/Resources/types"
          suffix: ~
