parameters:
  atoolo_resource.resource_root: '%env(RESOURCE_ROOT)%'

services:

  atoolo.resource.resourceChannelFactory:
    class: Atoolo\Resource\SiteKitResourceChannelFactory
    arguments:
      - '%atoolo_resource.resource_root%'

  atoolo.resource.resourceChannel:
    class: Atoolo\Resource\SiteKitResourceChannel
    factory: ['@atoolo.resource.resourceChannelFactory', 'create']

  atoolo.resource.resourceLoader:
    class: Atoolo\Resource\Loader\SiteKitLoader
    arguments:
      - '@atoolo.resource.resourceChannel'

  atoolo.resource.navigationHierarchyLoader:
    class: Atoolo\Resource\Loader\SiteKitNavigationHierarchyLoader
    arguments:
      - '@atoolo.resource.resourceLoader'
  atoolo.resource.categoryHierarchyLoader:
    class: Atoolo\Resource\Loader\SiteKitResourceHierarchyLoader
    arguments:
      - '@atoolo.resource.resourceLoader'
      - 'category'