Resource:
  type: "object"
  config:
    fields:
      id: { type: "ID!" }
      name: { type: "String!" }
      location: { type: "String!" }
      objectType: { type: "String!" }
      contentSectionTypes: { type: "[String!]" }
      teaser: { type: "Teaser!" }
      navigation: { type: "Hierarchy!" }
      kicker: { type: "String" }
      date: { type: "DateTime" }
      asset:
        type: "Asset"
        args:
          variant:
            type: "String"
      symbolicImage:
        type: "SymbolicImage"

Hierarchy:
  type: "object"
  config:
    fields:
      root: { type: "Resource!" }
      primaryParent: { type: "Resource" }
      primaryPath: { type: "[Resource!]" }
      children: { type: "[Resource!]" }

FacetGroup:
  type: "object"
  config:
    fields:
      key: { type: "String!" }
      facets: { type: "[Facet!]!" }

Facet:
  type: "object"
  config:
      fields:
        key: { type: "String!" }
        hits: { type: "Int!" }

SearchResult:
  type: "object"
  config:
      fields:
        total: { type: "Int!" }
        queryTime: { type: "Int!" }
        offset: { type: "Int!" }
        limit: { type: "Int!" }
        results: { type: "[Resource!]!" }
        facetGroups: { type: "[FacetGroup!]!" }

SuggestResult:
  type: "object"
  config:
    fields:
      suggestions: { type: "[Suggestion!]!" }
      queryTime: { type: "Int!" }

Suggestion:
  type: "object"
  config:
    fields:
      term: { type: "String!" }
      hits: { type: "Int!" }

Asset:
  type: "interface"
  config:
    fields:
      copyright: { type: "String" }
      caption: { type: "String" }
      description:  { type: "String" }

Image:
  type: "object"
  inherits: [Asset]
  config:
    interfaces: [Asset]
    fields:
      alternativeText: { type: "String" }
      original: { type: "ImageSource!" }
      characteristic: { type: "ImageCharacteristic" }
      sources: { type: "[ImageSource!]!" }

ImageSource:
  type: "object"
  config:
    fields:
      variant: { type: "String!" }
      url: { type: "String!" }
      width: { type: "Int!" }
      height: { type: "Int!" }
      mediaQuery: { type: "String" }

SymbolicImage:
  type: "object"
  inherits: [Asset]
  config:
    interfaces: [Asset]
    fields:
      url: { type: "String" }

IndexerStatus:
  type: "object"
  config:
    fields:
      startTime : { type: "DateTime" }
      endTime : { type: "DateTime" }
      lastUpdate : { type: "DateTime" }
      total: { type: "Int" }
      processed: { type: "Int" }
      skipped: { type: "Int" }
      updated: { type: "Int" }
      errors: { type: "Int" }
      statusLine: { type: "String" }

Link:
  type: "object"
  config:
    fields:
      url : { type: "String!" }
      label : { type: "String" }
      ariaLabel : { type: "String" }
      description: { type: "String" }
      opensNewWindow: { type: "Boolean!" }
      isExternal: { type: "Boolean!" }