MediaTeaserDecorator:
  type: "object"
  decorator: true
  inherits: [Teaser]
  config:
    interfaces: [Teaser]
    fields:
      headline: {type: String}
      text: {type: String}
      kicker: {type: String}
      contentType:  {type: String!}
      contentLength:  {type: Int!}
      asset:
        type: "Asset"
        args:
          variant:
            type: "String!"
            description: The teaser variant is used to decide which image format is to be returned.
        description: Teaser asset can be e.g. pictures or videos
      symbolicImage:
        type: "SymbolicImage"
        description: symbolic image associated with the teaser