TeaserDecorator:
  type: interface
  decorator: true
  config:
    fields:
      url:
        type: "String!"
        description: Teaser URL
        deprecationReason: use field 'link' instead
      link:
        type: "Link"
        description: Teaser Link
      opensNewWindow:
        type: "Boolean"
        description: if true, the teaser link should open a new tab/window
