TeaserDecorator:
  type: interface
  decorator: true
  config:
    fields:
      url:
        type: "String"
        description: Teaser URL
        deprecationReason: Use field 'link' instead
      link:
        type: "Link"
        description: Teaser Link
