name: E2E Test

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  e2etest:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger E2E Test
        run: |
          curl -XPOST -u "sitepark-bot:${{ secrets.BOT_PAT }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/sitepark/atoolo-e2e-test/actions/workflows/e2e-test.yml/dispatches --data '{"ref": "main"}'
