name: (📡) Verify

on:
  push:
    branches-ignore:
    - 'dependabot/**'
  pull_request:
    branches-ignore:
    - 'main'
  workflow_dispatch:

jobs:
  verify:
    uses: sitepark/github-project-workflow/.github/workflows/composer-verify.yml@release/1.x
    with:
      phpVersions: '["8.2","8.3","8.4"]'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
